services:
  - type: web
    name: shubdeep-wa-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: PORT
        value: 3000
    disk:
      name: wa-session-data
      mountPath: /app/auth_session
      sizeGB: 1
